name: code_entry_field
description: A Flutter widget for entering single characters at a time in a series of boxes.
version: 0.5.0
homepage: https://github.com/jvk75/code_entry_field

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
